language: node_js
node_js:
  - '8'
  - '9'
  - '10'
before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn install
before_script: greenkeeper-lockfile-update
script:
  - yarn run build
  - yarn run test
  - yarn run lint
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: BKZJ9+O8H+XipqPvdrr/hOKfstSz3HHKS0U7b0kFoteT/CICsX8BHdsEyg5IuV8xSYooWq7Wr1y9jLR38KW5D4eFEHElEpFRyQvWyflMDOZ8jJUH7gsCnYOcHkHiDsQgXMpmxO8Rj3XG3+cObri9TGLCowHpJdx9EbGFHrd2QiB5JREPlIJfXI2/1LItoOwtjRPsz+cIY1yNxmfzPYrr5b2OvFhvZBk4xSUf0Xtf8CRot+PjnLivgKy5Rhgq053VGTS4Hsc6EiC/nuvwxkGsTnH6LzFjwr/uotuXw9pBpU1jF9XGd88YjguXo9ITZdxHv4rSUUz/zKuKIIDiCRbK+8P7UPPCYA9JHZkkJAsot2ABx11FDeynnWi5nGmmkSF48Y9Z4ZjoSnZMf4UUUixqaF8GcYZcXDxxaSXwF3p6MMa/RjY9AekFCGokjJIV14HrjBjtdD99k4t31qmlxMICRsBkhOTbQYZ7VSgy00KDQOnqg7lW2CtPShp+YQ2BnU00mCJ2u/6LBdEKFjjmw8DdieOQBGpPVo/uaLQjav6U0HEoc7HNcjfaBs5UrHOZEM2FneSWD5Nbdwpfa+B17okedpldbgB5JjUYLjoSE8DGzqiW4MP7nVAaxGEyAgx0vSAIcT28VD/Xg3Wiprncxap318fDzL4AgM86PfEdgT8j490=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 10
env:
  global:
    secure: hn1pBPYFGn/08O5y5XX7jQuFErK48CPE19d6KpH3dHzIRco5KEFG2qGzpLwFZsPeXwvMYd+Pf27H8eXXpVn9AHNbMVPnkTCZCbvOBbRcGo/bnv/PW7xbsKRKANi0h6k8EkGJO9BtlH2OTeJZLGsW/FEm9zrqyrBoZDLB2ki2h+Q9uRwP0SqP0pROevB8OqsBwcmxuNtZ9033WEaMhHUr4Vj6sd4lKJD+8GNrRgGqVnNpRYk80jdd0fqPxhbp94I9Mh+EsxPTVZz0wZU/o61jouIoWPP1mokfrBakEnNEoNGF/Axk85f3Y02NQmGMyk7tMQCYQsG/pIy05LTM5U3+Kh29x8u6cfG89b32pERiU3L8cTAO7HhXijfJGp+DoqDFazBBJzmjq9QO/xmcGxNgtIxuo2oXZ7x7gE04jN9UOtQBv8qZNBS6yYWljrohTUMPHyqdqH94Qqv7YJPCE/ToAEDwMD8UonEYOHB+j0oY8tm3A0YEZQwvQruUur1yKSry8ZsmcpVimXqkkoAP8j6ooAnB6pRYZGSP54IeStlDbG88MfWFky2yxjPULu2c44qhXPlBJ/JMYKQLXUSwgsQcCenZb4w3tZbLINSVQb8PstT8OH/krt09sGBEXT7Yhs2d9X1I4k5tH4gQPmKkT31hIw7CGn/yNsTJ27Qi8Jr++LY=
