language: node_js
node_js:
- '9'
- '8'
- '7'
install:
- yarn install
- yarn run build
script:
- yarn run test
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: rZJM4qi4RSLUH7nwJn9+vJhVxG6lkEeNL7KFEbadGnznJsloklSgObbnK31WQAdhgvv2fXlfxH7rKmlwfhVfoj6bVA9/W/S9SzplEs/zYiEM29O1QeWdJzXS8Ao9LaV+CMu/T/XmXZa6gmW1FP74nOzxyncnWmI6u+fxAFNbUFNKTo6cYfX3ixcEC/cX8X+HmJrJfFlgo2vXu+ouP5klFw0VAaz3tqUZRnMXbkKpWp8AH66f5IRxPpnjX9qaC3qs85QvGbn0+C16wp64cGy0ht/QRVF6QeKWV1UJkCo78vl2sQ30ny+3G/Uzk6BTXkIP6Sow89zhf2JekVPNlEdJ+XvoGIcEzutafY2IZq3ECbk17bobkO7akfy+XC0ww4EosdCstHwujgZpOdRKOtocoRW7YTaGmpsBPviaFsTEdX8PcbINwJwCCU4DiW2U69+4P8tIWh/boG/jeSzjH8uZbFD9TDVvGn/Ou34RinrwOUIOZEDpMjMEjy7sxS8nH5JTLOhU0j6JsleHBzdoY+s+ZMVxc2Qv3uKcDgal4NdzmTTCvK/O0/BqYkJUssohIuKKEqrzoEKeiJ+Y/fsXmH4hlZwHV93fPM8bI9HuKM3PzXhbtWjXf7UtOrBsKjLkQvH8X6hxl3KmFX2Mv9HzJ6Iq1e9CrQr2cmubkZXL7bZhpxU=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 9
