language: node_js
node_js:
  - '9'
  - '8'
  - '7'
  - '10'
before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn install
before_script: greenkeeper-lockfile-update
script:
  - yarn run build
  - yarn run test
  - yarn run lint
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: rZJM4qi4RSLUH7nwJn9+vJhVxG6lkEeNL7KFEbadGnznJsloklSgObbnK31WQAdhgvv2fXlfxH7rKmlwfhVfoj6bVA9/W/S9SzplEs/zYiEM29O1QeWdJzXS8Ao9LaV+CMu/T/XmXZa6gmW1FP74nOzxyncnWmI6u+fxAFNbUFNKTo6cYfX3ixcEC/cX8X+HmJrJfFlgo2vXu+ouP5klFw0VAaz3tqUZRnMXbkKpWp8AH66f5IRxPpnjX9qaC3qs85QvGbn0+C16wp64cGy0ht/QRVF6QeKWV1UJkCo78vl2sQ30ny+3G/Uzk6BTXkIP6Sow89zhf2JekVPNlEdJ+XvoGIcEzutafY2IZq3ECbk17bobkO7akfy+XC0ww4EosdCstHwujgZpOdRKOtocoRW7YTaGmpsBPviaFsTEdX8PcbINwJwCCU4DiW2U69+4P8tIWh/boG/jeSzjH8uZbFD9TDVvGn/Ou34RinrwOUIOZEDpMjMEjy7sxS8nH5JTLOhU0j6JsleHBzdoY+s+ZMVxc2Qv3uKcDgal4NdzmTTCvK/O0/BqYkJUssohIuKKEqrzoEKeiJ+Y/fsXmH4hlZwHV93fPM8bI9HuKM3PzXhbtWjXf7UtOrBsKjLkQvH8X6hxl3KmFX2Mv9HzJ6Iq1e9CrQr2cmubkZXL7bZhpxU=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 9
env:
  global:
    secure: hn1pBPYFGn/08O5y5XX7jQuFErK48CPE19d6KpH3dHzIRco5KEFG2qGzpLwFZsPeXwvMYd+Pf27H8eXXpVn9AHNbMVPnkTCZCbvOBbRcGo/bnv/PW7xbsKRKANi0h6k8EkGJO9BtlH2OTeJZLGsW/FEm9zrqyrBoZDLB2ki2h+Q9uRwP0SqP0pROevB8OqsBwcmxuNtZ9033WEaMhHUr4Vj6sd4lKJD+8GNrRgGqVnNpRYk80jdd0fqPxhbp94I9Mh+EsxPTVZz0wZU/o61jouIoWPP1mokfrBakEnNEoNGF/Axk85f3Y02NQmGMyk7tMQCYQsG/pIy05LTM5U3+Kh29x8u6cfG89b32pERiU3L8cTAO7HhXijfJGp+DoqDFazBBJzmjq9QO/xmcGxNgtIxuo2oXZ7x7gE04jN9UOtQBv8qZNBS6yYWljrohTUMPHyqdqH94Qqv7YJPCE/ToAEDwMD8UonEYOHB+j0oY8tm3A0YEZQwvQruUur1yKSry8ZsmcpVimXqkkoAP8j6ooAnB6pRYZGSP54IeStlDbG88MfWFky2yxjPULu2c44qhXPlBJ/JMYKQLXUSwgsQcCenZb4w3tZbLINSVQb8PstT8OH/krt09sGBEXT7Yhs2d9X1I4k5tH4gQPmKkT31hIw7CGn/yNsTJ27Qi8Jr++LY=
